In [1]:
import tensorflow as tf

In [2]:

from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=10000

In [10]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7351, 2244, 9690, 8685], [7351, 2244, 9690, 1611], [7351, 2784, 9690, 6049], [8600, 4083, 2934, 6072, 8050], [8600, 4083, 2934, 6072, 7317], [6085, 7351, 5306, 9690, 6107], [9667, 3885, 8487, 6072]]


In [11]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:

import numpy as np

In [13]:

sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
# To use pad sequences make sure size of the sentences is same
# S for this we are using padding 'pre' so that it will add 0s where words are not present in the sentences
#this will make the sent_length or sentence length to be 8 a mentioned

[[   0    0    0    0 7351 2244 9690 8685]
 [   0    0    0    0 7351 2244 9690 1611]
 [   0    0    0    0 7351 2784 9690 6049]
 [   0    0    0 8600 4083 2934 6072 8050]
 [   0    0    0 8600 4083 2934 6072 7317]
 [   0    0    0 6085 7351 5306 9690 6107]
 [   0    0    0    0 9667 3885 8487 6072]]


In [14]:
dim=10

In [15]:

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:

print(model.predict(embedded_docs))

[[[-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893
   -0.01538236  0.03580565  0.01945036 -0.01206756 -0.01748126]
  [-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893
   -0.01538236  0.03580565  0.01945036 -0.01206756 -0.01748126]
  [-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893
   -0.01538236  0.03580565  0.01945036 -0.01206756 -0.01748126]
  [-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893
   -0.01538236  0.03580565  0.01945036 -0.01206756 -0.01748126]
  [ 0.03561291 -0.0116369  -0.02263211  0.04579603 -0.04972465
    0.00293621  0.03325356 -0.00260837 -0.01120385 -0.04736543]
  [-0.04727317 -0.02928734  0.00973289 -0.02310399 -0.02284522
    0.00986327  0.02027149 -0.00257581 -0.02717288 -0.02255417]
  [ 0.01824171 -0.02195176 -0.04664515 -0.00053904 -0.01666615
    0.03853167 -0.00998763 -0.03290911 -0.00156556  0.04543721]
  [-0.0496496   0.00364604 -0.01585176 -0.0121262   0.00472903
    0.02186782  0.01778648 -0.04856552 -0.042998

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 7351, 2244, 9690, 8685])

In [20]:
print(model.predict(embedded_docs)[0])

[[-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893 -0.01538236
   0.03580565  0.01945036 -0.01206756 -0.01748126]
 [-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893 -0.01538236
   0.03580565  0.01945036 -0.01206756 -0.01748126]
 [-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893 -0.01538236
   0.03580565  0.01945036 -0.01206756 -0.01748126]
 [-0.017444    0.00027718 -0.01069863 -0.04533656  0.00207893 -0.01538236
   0.03580565  0.01945036 -0.01206756 -0.01748126]
 [ 0.03561291 -0.0116369  -0.02263211  0.04579603 -0.04972465  0.00293621
   0.03325356 -0.00260837 -0.01120385 -0.04736543]
 [-0.04727317 -0.02928734  0.00973289 -0.02310399 -0.02284522  0.00986327
   0.02027149 -0.00257581 -0.02717288 -0.02255417]
 [ 0.01824171 -0.02195176 -0.04664515 -0.00053904 -0.01666615  0.03853167
  -0.00998763 -0.03290911 -0.00156556  0.04543721]
 [-0.0496496   0.00364604 -0.01585176 -0.0121262   0.00472903  0.02186782
   0.01778648 -0.04856552 -0.04299836  0.040386  ]]